tonkec/duga_frontend_v2

- src/components/LatestMessages/index.tsx
- show message as unread in lates messages on dashboard
- mark unread message as read when user clicks on the message
- change background color of the message based on read/unread status
> feature(read-in-latest): mark as read messages in latest messages

- src/components/PhotoUploader/index.tsx
- https://trello.com/c/cmTYOeyp/66-uploads-undefined-id
- prevent uploads to have undefined id
- fix was found here https://stackoverflow.com/a/62726266/2504334
> fix(bug/uploads-undefined-id): reorder fields

- src/App.tsx
- src/components/LatestComments/index.tsx
- src/components/LatestMessages/index.tsx
- src/components/LatestUploads/index.tsx
- src/components/UserFilters/index.tsx
- fix dropdown width in dashboard
- in dashboard, hide sections if there is not enough data to display
- remove ugly not found image if there is no data
> feat(feat/improve-dashboard): improve paddings

- src/api/notifications/index.ts
- src/components/Navigation/components/Notifications/index.tsx
- src/components/Navigation/hooks/index.ts
- src/components/Navigation/index.tsx
- src/components/PhotoComments/components/CommentWithUser.tsx
- src/components/PhotoLikes/hooks/index.ts
- src/components/PhotoLikes/index.tsx
- do not merge until https://github.com/tonkec/duga_backend/pull/2 is merged
- add notifications for 
- new comments on uploads
- new likes on uploads
- new messages
> feat(notifications): render first notifications

- src/App.tsx
- src/components/Footer/index.tsx
Na početnoj stranici u karticu `Želiš li nam pomoći` dodan je link na github projekt contribution paragraf. Isto je dodano u footer za tekst `Kodiraš? Pomozi nam unaprijediti aplikaciju!`
> link na github dodan u footer i u karticu na početnoj stranici

- src/App.tsx
- src/pages/Login/hooks/index.ts
- navigate to login screen if there is no user id from BE
> fix(user-without-id): show error message if there is no user id

- src/components/PhotoLikes/components/LikesList/index.tsx
- src/components/PhotoLikes/index.tsx
- add dropdown for photo likes
> feature(photo-likes-users): add photo likes dropdown

- src/pages/ChatPage/components/Message/index.tsx
Removed the extra background color of chat messages that was not needed.
> Fixing the background color of chat messages

- src/App.tsx
- src/pages/EditMyProfilePage/index.tsx
- lowercase username to match the one in DB
> bug(lowercased-username): make sure username is always lowercased

- package-lock.json
- package.json
- src/api/chatMessages/index.ts
- src/components/GiphySearch/hooks/index.ts
- src/components/GiphySearch/index.tsx
- src/pages/ChatPage/components/SendMessage/index.tsx
- src/utils/consts.ts
- GIPHY support
- Pagination: limit 8 gifs
- If search input is blank, trending gifs are shown
> GIPHY integration

- src/components/EmojiPicker/index.tsx
Adding style changes to the emoji picker in chat messages.
- dropdown look
- grid layout
- scroll behavior 
- positioning absolute
- lightening the background
- hover effect
> Improve emoji picker style

- package-lock.json
- package.json
- src/api/uploadsComments/index.ts
- src/api/users/index.ts
- src/components/LatestComments/index.tsx
- src/components/MentionInput/hooks/index.ts
- src/components/MentionInput/index.tsx
- src/components/PhotoComments/components/CommentWithUser.tsx
- src/components/PhotoComments/hooks/index.ts
- src/components/PhotoComments/index.tsx
- do not merge until https://github.com/tonkec/duga_backend/pull/8 is merged 
- show dropdown with usernames
- send notification when someone gets mentioned
> feature(tagging-users): tag users in comments

- src/api/users/index.ts
- fix path for fetching username
> hotfix(revert-endpoint-path): add username to path

- package-lock.json
- package.json
- src/components/Navigation/components/OnlineStatus/index.tsx
- src/components/Navigation/index.tsx
- src/components/UserCard/index.tsx
- src/components/UserProfileCard/index.tsx
- src/context/OnlineStatus/index.tsx
- src/context/OnlineStatus/useStatusMap.ts
- src/main.tsx
- src/pages/ChatPage/index.tsx
- show online/offline dot in user card
- add dropdown to enable users to toggle their online/offline status
- do not merge until https://github.com/tonkec/duga_backend/pull/5 is merged
> feature(online-offline): add online/offline dropdown

- cypress.config.mjs
- cypress/e2e/spec.cy.js
- cypress/fixtures/example.json
- cypress/support/commands.ts
- cypress/support/e2e.ts
- package-lock.json
- package.json
> Cypress init with npm only

- src/api/users/index.ts
- src/components/Navigation/components/OnlineStatus/index.tsx
- src/components/UserProfileCard/index.tsx
- src/context/OnlineStatus/hooks/index.ts
- src/context/OnlineStatus/index.tsx
- do not merge until https://github.com/tonkec/duga_backend/pull/13 is merged
- sync dropdown with online/offline status with the one from db
> bug(online-status): read online status from db on mount

- src/pages/ChatPage/components/PaginatedMessages/index.tsx
Adjusting Chat Message Visibility
- Set a height for the chat container to ensure the latest message is always visible. 
- The container now scrolls automatically to display new messages.
> Scroll to latest message

- src/components/Paginated/index.tsx
Showing proper comments count if you are on pagination limit
> Fixed bug with comments

- src/pages/ChatPage/index.tsx
- https://trello.com/c/BuJUZZkm/100-deleting-a-chat-notification-error
> bug(deleting-chat): remove redirect to unexisting page

- src/components/PhotoUploader/index.tsx
- allow empty description for photos
> bug(delete-photo-description): allow empty description

- src/components/PhotoLikes/components/LikesList/index.tsx
- check if there are likes
- if there are no likes show `0 lajkova`
> bug(dislike): fix disliking the photo

- src/components/PhotoUploader/index.tsx
- remove photo from state preview after the photo is uplaoded
> bug(remove-photo): remove photo from state after upload

- src/components/PhotoComments/index.tsx
- src/pages/ChatPage/components/SendMessage/index.tsx
- added emojis to comment section
> feat(comment-emojis): add emojis to photo comments

- src/components/PhotoComments/index.tsx
- src/pages/ChatPage/components/SendMessage/index.tsx
- https://trello.com/c/x1OkkTld#comment-68273bdf69cd51eac2dd7c02
> task(comment-max-images): enable users to add comments without images

- src/components/EmojiPicker/index.tsx
- corrected margin for better positioning
> fixed positioning of emojis dropdown menu 
